server:
  port: 3500
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost/batch
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

  mail:
    host: smtp.gmail.com
    username: batchmanagingsystem.cri@gmail.com
    password: xjsqoobgmpmtrfkp
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
